export enum HttpResponseStatus {
  OK = "OK",
  CREATED = "CREATED",
  NOT_FOUND = "NOT FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR",
  BAD_REQUEST = "BAD REQUEST",
  METHOD_NOT_ALLOWED = "METHOD NOT ALLOWED",
}
